[package]
name = "cugparck-gpu"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cugparck-commons = { path = "../commons" }
cuda_std = "0.2.1"

[build-dependencies]
cc = "1.0.71"