[profile.release]
strip = true
lto = true
codegen-units = 1

[workspace]
resolver = "2"

members = ["cli", "core", "cpu", "cubecl"]

[patch.crates-io]
indexmap = { git = "https://github.com/truelossless/indexmap" }
