cargo-features = ["strip"]

[profile.release]
strip = true
lto = true
codegen-units = 1

[workspace]
resolver = "2"

members = [
    "cli",
    "commons",
    "cpu",
]

[patch.crates-io]
indexmap = { git = "https://github.com/truelossless/indexmap" }