[package]
name = "cugparck-cpu"
version = "0.4.0"
edition = "2021"

[dependencies]
cugparck-commons = { path = "../commons"}
wgpu = { version = "0.13.1", features = ["spirv"] }
bytemuck = "1.12.1"
pollster = "0.2.5"
thiserror = "1.0.24"
bytecheck = "0.6.8"
rkyv = { version = "0.7.39", default-features = false, features = ["alloc", "std", "validation", "size_64", "tinyvec", "copy_unsafe"] }
memmap2 = "0.5.5"
cust = { version = "0.3.2", optional = true }
bitvec = "1.0.0"
rayon = "1.5.3"
crossbeam-channel = "0.5.5"
itertools = "0.10.3"
nohash-hasher = "0.2.0"

[features]
cuda = ["cust", "cugparck-commons/cuda"]
