[package]
name = "spirv"
version = "0.5.0"
edition = "2021"

[lib]
crate-type = ["dylib", "lib"]

[dependencies]
cugparck-commons = { path = "../commons" }
spirv-std = { version = "0.4.0-alpha.14", features = ["glam"] }

[workspace]