name: Release

on:
  push:
    tags: ["v*.*.*"]
    paths-ignore:
      - "**.md"

env:
  CUDA_VERSION: "12.1.1"
  BINARY_NAME: cugparck-cli

jobs:
  build_release_binaries:
    name: Build release binary (${{ matrix.target }})
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-x86_64
            asset_name_suffix: ""
          - os: windows-latest
            target: windows-x86_64
            asset_name_suffix: ".exe"
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install CUDA Toolkit
        uses: Jimver/cuda-toolkit@v0.2.24
        id: cuda-toolkit
        with:
          cuda: ${{ env.CUDA_VERSION }}

      - name: Cache Cargo dependencies for release build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release binary
        run: cargo build --release --verbose

      - name: Prepare release artifact
        shell: bash
        run: |
          ASSET_NAME="${{ env.BINARY_NAME }}-${{ github.ref_name }}-${{ matrix.target }}${{ matrix.asset_name_suffix }}"
          mv "target/release/${{ env.BINARY_NAME }}${{ matrix.asset_name_suffix }}" "$ASSET_NAME"
          echo "ASSET_PATH=$ASSET_NAME" >> $GITHUB_ENV

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ASSET_PATH }}
          path: ${{ env.ASSET_PATH }}

  publish_release:
    name: Publish GitHub release
    needs: build_release_binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all release artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: Update changelog
        id: changelog
        uses: requarks/changelog-action@v1.10.2
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          writeToFile: false

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2.3.2
        with:
          body: ${{ steps.changelog.outputs.changes }}
          files: |
            release-artifacts/**/cugparck-cli*
