on:
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            target: linux
            ext: ""
          - os: windows-latest
            target: windows
            ext: .exe
    name: ${{ matrix.target }} tests
    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install CUDA
        uses: Jimver/cuda-toolkit@v0.2.8
        with:
          cuda: "11.2.2"

      - name: Populate env
        if: contains(matrix.os, 'ubuntu')
        run: |
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CUDA_PATH/compat:$CUDA_PATH/nvvm/lib64" >> $GITHUB_ENV
          echo "LLVM_LINK_SHARED=1" >> $GITHUB_ENV

      - name: Install LLVM 7
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install llvm-7
          sudo ln -s /usr/bin/llvm-config-7 /usr/local/bin/llvm-config

      - name: Install Rust-CUDA toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-12-04
          components: rust-src, rustc-dev, llvm-tools-preview

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true

      - name: Load rust Cache
        uses: Swatinem/rust-cache@v1

      - name: Run tests
        run: cargo test --release --no-fail-fast
